// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgQFN7nut78AG3SDTG1foz12X-soNqRrY',
    appId: '1:782037911215:web:1ff073e7ce0a057ddeb65a',
    messagingSenderId: '782037911215',
    projectId: 'sight-ai-f61b1',
    authDomain: 'sight-ai-f61b1.firebaseapp.com',
    storageBucket: 'sight-ai-f61b1.firebasestorage.app',
    measurementId: 'G-2D052EQR5Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFOp1o1upjtALF41G13qkQ99Ed4zt2VrE',
    appId: '1:782037911215:android:77408cc66e175d0adeb65a',
    messagingSenderId: '782037911215',
    projectId: 'sight-ai-f61b1',
    storageBucket: 'sight-ai-f61b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaIX5LDd_sUs6ETeM9blgIOxmHYa5v9To',
    appId: '1:782037911215:ios:0413572e28f376eadeb65a',
    messagingSenderId: '782037911215',
    projectId: 'sight-ai-f61b1',
    storageBucket: 'sight-ai-f61b1.firebasestorage.app',
    iosBundleId: 'com.example.sightaiPrototype',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaIX5LDd_sUs6ETeM9blgIOxmHYa5v9To',
    appId: '1:782037911215:ios:0413572e28f376eadeb65a',
    messagingSenderId: '782037911215',
    projectId: 'sight-ai-f61b1',
    storageBucket: 'sight-ai-f61b1.firebasestorage.app',
    iosBundleId: 'com.example.sightaiPrototype',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgQFN7nut78AG3SDTG1foz12X-soNqRrY',
    appId: '1:782037911215:web:9d5fd7ab3b49c168deb65a',
    messagingSenderId: '782037911215',
    projectId: 'sight-ai-f61b1',
    authDomain: 'sight-ai-f61b1.firebaseapp.com',
    storageBucket: 'sight-ai-f61b1.firebasestorage.app',
    measurementId: 'G-KGHVMEB2TV',
  );

}